//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long ID { get; set; }
        public Nullable<byte> ImageType { get; set; }
        public Nullable<byte> seq { get; set; }
        public Nullable<long> ImageApplyID { get; set; }
        public string ImageLocation { get; set; }
    }
}
