//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Objects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipiesDbEntities : DbContext
    {
        public RecipiesDbEntities()
            : base("name=RecipiesDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<RecipieDirection> RecipieDirections { get; set; }
        public virtual DbSet<RecipieIngredient> RecipieIngredients { get; set; }
        public virtual DbSet<Recipy> Recipies { get; set; }
        public virtual DbSet<UnitsOfMeasurement> UnitsOfMeasurements { get; set; }
        public virtual DbSet<UserRecipieBookMark> UserRecipieBookMarks { get; set; }
        public virtual DbSet<UserRecipieRating> UserRecipieRatings { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
