//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDirection
    {
        public long ID { get; set; }
        public Nullable<short> Step { get; set; }
        public string StepInstructions { get; set; }
        public Nullable<byte> TimeSpanHours { get; set; }
        public Nullable<byte> TimeSpanMinutes { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
