//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public long ID { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
