//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipy()
        {
            this.RecipieDirections = new HashSet<RecipieDirection>();
            this.RecipieIngredients = new HashSet<RecipieIngredient>();
            this.UserRecipieBookMarks = new HashSet<UserRecipieBookMark>();
            this.UserRecipieRatings = new HashSet<UserRecipieRating>();
        }
    
        public long ID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> TotalTimeNeededHours { get; set; }
        public Nullable<byte> TotalTimeNeededMinutes { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<decimal> AverageRecipieRating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipieDirection> RecipieDirections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipieIngredient> RecipieIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRecipieBookMark> UserRecipieBookMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRecipieRating> UserRecipieRatings { get; set; }
    }
}
